# Save into your repo as .github/workflows/on-tag.yaml
name: On Tag
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: acorn-io/actions-setup@v1
      - uses: acorn-io/actions-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        run: |
          acorn build -t ghcr.io/${{ github.repository }}:main .
          acorn push ghcr.io/${{ github.repository }}:main
